### ISSUE TITLE
Create MultivariateCoupledNormal distribution class

### ISSUE THREAD

**Issue by Kevin-Chen0** [Photrek/Nonlinear-Statistical-Coupling#16]
Create a MultivariateCoupledNormal distribution class that takes in coupling value `kappa` and number of dimensions `dim`, and includes the following functions:

1. `log_prob`. See our latest nsc code [here](https://github.com/kenricnelson/Nonlinear-Statistical-Coupling/blob/master/nsc/distribution/multivariate_coupled_normal.py#L250-L251).

2. `sample_n`. See our latest nsc code [here](https://github.com/kenricnelson/Nonlinear-Statistical-Coupling/blob/master/nsc/distribution/multivariate_coupled_normal.py#L213-L230).

3. `entropy`. See our latest nsc code [here](https://github.com/kenricnelson/Nonlinear-Statistical-Coupling/blob/master/nsc/distribution/multivariate_coupled_normal.py#L253-L265).

4. `kl_multcouplednormal_multcouplednormal`. Or the KL-Divergence function for two MultivariateCoupledNormal distributions. 

Use the respective CoupledNormal functions as a foundation to build the MultivariateCoupledNormal ones.

**Comment by kenricnelson** [comment]
Univariate CoupledNormal is complete

**Comment by kenricnelson** [comment]
MultivariateCoupledNormal is in progress

**Comment by Kevin-Chen0** [comment]
Closing old issue. This has been completed.
