### ISSUE TITLE
Interesting behaviour in coupled exponential with negative Kappa

### ISSUE THREAD

**Issue by hxyue1** [Photrek/Nonlinear-Statistical-Coupling#19]
Reporting some of the results I talked about with John, Bill and Kevin with regards to negative Kappa values

![image](https://user-images.githubusercontent.com/42855604/119208229-13f96f80-ba56-11eb-980a-72b995561047.png)

For -1< kappa <0, there are domain restriction on the input values. When kappa < -1, the shape of the exponential inverts and stop at the x-axis. At kappa = -1, it's a straight line which extends from -inf to 1.

Code to reproduce

```
X = np.linspace(-10, 5, n_sample*10)
y = {}

fig, ax = plt.subplots(figsize=(8, 12))
ax.axvline(c='black', lw=1)
ax.axhline(c='black', lw=1)

cm = plt.get_cmap('PiYG')
kappa_values = [round(value, 1) for value in np.arange(-2, -0.4, 0.2)]
n = len(kappa_values)

plt.xlim(-10, 10)
plt.ylim(-10, 10)

for kappa in kappa_values:
    y[kappa] = nsc.exp(X, kappa)
    plt.plot(X, y[kappa], label=kappa)

plt.legend()
plt.show();
```

I will comment more results in this issue as I continue to find them.

**Comment by hxyue1** [comment]
For -1<kappa<0, the coupled exponential has an asymptote at x=-1/kappa. While I'm sure this is consistent with the intended mathematical expression, it might be a good idea to add some warnings.

Here's an example for kappa = -0.8, it has an asymptote of x=1.25.

![image](https://user-images.githubusercontent.com/42855604/119896922-966dad80-bef4-11eb-83f8-7ccfad3d7dc7.png)

Another example for kappa =-0.5, the asymptote is at x=2.

![image](https://user-images.githubusercontent.com/42855604/119897026-b309e580-bef4-11eb-9098-ea1b392e8db7.png)

The code to reproduce the first example is below

```
kappa = -0.8
asymptote = -1/kappa
x = np.linspace(-10, asymptote-0.01, 10000)

#Augmenting x to better capture the asymptotic behaviour
sig_figs = 8
start = 10
end = start**sig_figs

x_aug = asymptote - 1/np.geomspace(start, end, num=sig_figs)
x = np.append(x,x_aug[2:])

y = nsc.exp(x, kappa)

fig, ax = plt.subplots(figsize=(12, 8))
ax.plot(x, y, label='Kappa = ' + str(kappa))

ax.axvline(c='black', lw=1)
ax.axhline(c='black', lw=1)

#Drawing the asymptote
ax.axvline(x=asymptote, c='black', lw=1, ls='--', label='x = ' + str(asymptote))

ax.set_xlim(-5, 2)
ax.set_ylim(-2, 10)

ax.legend()

**Comment by Kevin-Chen0** [comment]
This issue has been resolved
