### ISSUE TITLE
Applications of Coupled VAE

### ISSUE THREAD

**Issue by kenricnelson** [Photrek/Nonlinear-Statistical-Coupling#2]
We needed a clear plan of how we will demonstrate the capabilities of the Coupled VAE. This issue can address both short-term demonstrations which we complete for the current paper and longer-term interests in applications that potential sponsors would be interested in.

For the short-term:
1) We are planning to use the CIFAR-10 dataset to demonstrate close to the state-of-the-art capabilities with the Coupled VAE; however, there are concerns that the current architecture will not be adequate to train against these complex images. Therefore, there is a need to
2) Review the literature on the use of VAE to learn, classify, and generate CIFAR images.
3) Take detailed notes in Mendeley of these articles so others on the team can quickly review the key points for our project
4) Write a good summary of the approaches that can be used to both decide on our best approach and be used in the paper we are working on.

For longer-term issues
1) This should be lower priority until we have a good review of processing CIFAR-10 with VAEs
2) Can be broader in scope including using VAEs for processes, including signal processing, image processing, and natural language processing
3) Goal is to both motivate a new project following the current paper and to help the team develop sponsorship for the research

**Comment by Thistleton** [comment]
Possible area of application: use of VAE for Anomaly Detection, especially in  images and time series. 41 articles available on arxiv for 

+"VAE"  
+"Anomaly Detection"

No articles also contain +"student", so possible innovation area for coupled gaussians

**Comment by Kevin-Chen0** [comment]
Closing issue.
