### ISSUE TITLE
Failed to use np.apply_along_axis for MNC prob with batches

### ISSUE THREAD

**Issue by Kevin-Chen0** [Photrek/Nonlinear-Statistical-Coupling#20]
Initially, I have tried to use the following lambda function in MNC [prob](https://github.com/Photrek/Nonlinear-Statistical-Coupling/blob/master/nsc/distributions/multivariate_coupled_normal.py#L114-L118):

```
            _normalized_X = lambda x: np.matmul(np.matmul(np.expand_dims(x-self._loc, axis=-2),
                                                          _sigma_inv
                                                          ),
                                                np.expand_dims(x-self._loc, axis=-1)
                                                )

```
However, when doing so, I get the following error:

```
X_norm = np.apply_along_axis(_normalized_X, 1, X)
*** ValueError: operands could not be broadcast together with shapes (64,) (64,2)
```

Therefore, as a work-around, I have to use the following [for-loop](https://github.com/Photrek/Nonlinear-Statistical-Coupling/blob/master/nsc/distributions/multivariate_coupled_normal.py#L109-L113) in order to populate X_norm. Nevertheless, I still believe that this can be done through vectorization, for example, using an alternative func other than `np.apply_along_axis`.

**Comment by hxyue1** [comment]
Can you provide a test case and the original code which didn't work?
