### ISSUE TITLE
Coupled KL Divergence does not support batches

### ISSUE THREAD

**Issue by Kevin-Chen0** [Photrek/Nonlinear-Statistical-Coupling#23]
I have created two `MultivariateCoupledNormal` distributions, both of bach_size=32 batches and dim=2. However, I get the following error when performing `coupled_kl_divergence`:

![image](https://user-images.githubusercontent.com/13785749/122663458-9b76f300-d168-11eb-9525-aeaeed2805da.png)

**Comment by jkclem** [comment]
This issue is resolved and can be closed.
