### ISSUE TITLE
Mixture Model for Coupled VAE

### ISSUE THREAD

**Issue by kenricnelson** [Photrek/Nonlinear-Statistical-Coupling#3]
To enable processing of CIFAR10 with the Coupled VAE a variety of enhancements are required. One critical one is to incorporate supervised learning with labels for the 10 classes of the CIFAR images. The labeling will allow each class to be trained with its own Coupled VAE latent layer. This is one step toward reducing the complexity of the dataset. Other steps will be required but let's complete this step first.

1) Review carefully the Boenninghoff paper on Student t Mixture Model VAE and related papers particularly the following reference: J. Domke and D. Sheldon, “Importance Weighting and Variational Inference,” in 32nd Conference on Neural Information Processing Systems (NeurIPS 2018), 2018.

2) Determine and specify what changes are needed in both the architecture of the VAE and the cost functions of the VAE.

3) Collaborate with John Clements on a plan to implement this change.

**Comment by kenricnelson** [comment]
This needs to be deferred until we have completed the core library.

**Comment by Kevin-Chen0** [comment]
I have reassigned this research to Daniel.

**Comment by Kevin-Chen0** [comment]
Closing issue.

**Comment by Kevin-Chen0** [comment]
Closing old issue.
