### ISSUE TITLE
Processes for Coupled VAE

### ISSUE THREAD

**Issue by kenricnelson** [Photrek/Nonlinear-Statistical-Coupling#4]
1) Support team in the implementation of effective numerical methods for the core Coupled Functions, particularly the current issue regarding integration for the entropy functions.

2) Provide guidance for Daniel Svoboda in completing a well-written review of applications of Coupled VAEs

3) Develop a plan for applying the Coupled VAE to a variety of processes (signal, image, and natural language).

**Comment by kenricnelson** [comment]
Dec 22, 2020

Step 1 is underway.
Step 2 looking forward to working with Daniel.
Step 3 is a longer-term goal.

**Comment by Kevin-Chen0** [comment]
Closing old issue.
