### ISSUE TITLE
Limited range of convergence for current Coupled VAE implementation

### ISSUE THREAD

**Issue by kenricnelson** [Photrek/Nonlinear-Statistical-Coupling#5]
Given the current issue regarding the limited range convergence for the Coupled VAE investigate two potential resolutions:

1) Does taking the root of the entropy function give sufficient stability to the quantification of generalized entropy such that the training of machine learning algorithms can converge of a broader range of coupling values.  If this is the case plan to priorities use of the root in defining the Coupled Entropy and draft a paper that introduces the importance of this definition for generalized entropy.

2) Develop a better understand how the incorporation of the generalized cost functions into machine learning affects the gradient descent algorithms used in the training process.

3) Given the literature on Wasserstein metric for machine learning, determine exactly what the distinction if any is from the generalized mean. If these are closely related, or possibly equal, than clarify how the generalized mean could be used as a cost function rather than the generalized entropy functions.

**Comment by Kevin-Chen0** [comment]
Closing old issue.
